const foots = {
  1: {
    food_name: "Jameson Irish Whiskey",
    food_category: "grain",
    food_price: 50.3,
    food_expiration_date: "11/1/2023",
    food_origin: "Japan",
  },
  2: {
    food_name: "Apple - Fuji",
    food_category: "fruit",
    food_price: 11.42,
    food_expiration_date: "12/26/2023",
    food_origin: "Indonesia",
  },
  3: {
    food_name: "Cleaner - Bleach",
    food_category: "dairy",
    food_price: 21.36,
    food_expiration_date: "9/3/2023",
    food_origin: "Greece",
  },
  4: {
    food_name: "Mace Ground",
    food_category: "vegetable",
    food_price: 80.05,
    food_expiration_date: "6/9/2023",
    food_origin: "Philippines",
  },
  5: {
    food_name: "Appetizer - Assorted Box",
    food_category: "fruit",
    food_price: 17.79,
    food_expiration_date: "1/4/2023",
    food_origin: "Poland",
  },
  6: {
    food_name: "Beans - Fava, Canned",
    food_category: "fruit",
    food_price: 75.68,
    food_expiration_date: "2/21/2023",
    food_origin: "Indonesia",
  },
  7: {
    food_name: "Wine - White, Chardonnay",
    food_category: "meat",
    food_price: 34.41,
    food_expiration_date: "2/10/2023",
    food_origin: "Indonesia",
  },
  8: {
    food_name: "Chicken - Wings, Tip Off",
    food_category: "grain",
    food_price: 77.36,
    food_expiration_date: "2/22/2023",
    food_origin: "Indonesia",
  },
  9: {
    food_name: "Pomello",
    food_category: "fruit",
    food_price: 15.64,
    food_expiration_date: "2/10/2023",
    food_origin: "Morocco",
  },
  10: {
    food_name: "Pastry - Chocolate Chip Muffin",
    food_category: "grain",
    food_price: 93.32,
    food_expiration_date: "7/23/2023",
    food_origin: "Poland",
  },
};
